version: '3.4'

services:
    bidaf_na:
        image: ankurgos/bidaf:latest
        volumes:
            - ${DATA_DIR}:/data
        command: 'bash -c ./run2.sh'

    bidaf:
        image: ankurgos/bidaf:latest
        volumes:
            - ${DATA_DIR}:/data
        command: 'bash -c ./run.sh'

